### ISSUE TITLE
Efficiency problem due to the for loops

### ISSUE THREAD

**Issue by Archer-Tatsu** [jonas-koehler/s2cnn#10]
First thank you for publishing this useful code!
However, when I was implementing this code, I found that it run very slow with high CPU usage and no GPU usage. I finally find out that in some functions, such as `_setup_s2_ft` and `_setup_s2_fft`, there are for loops so that if the given `bandwidth` is a large number (I want to let it be 256), it takes very long time to run the function, like:
```
_setup_s2_fft(256, 256, True)... done in 10535 seconds
_setup_s2_ft(256, ((1.5707963267948966, 0.0), (1.5707963267948966, 0.01227184630308513), ...), device_type='cuda', device_index=0)... done in 11894 seconds
```
Did you ever tried a large bandwidth in practice?  Is there any better way to obtain the results of these functions? (Maybe with utilization of GPU?)

**Comment by tscohen** [comment]
Yes, running these can take a long time, and it is likely that they can be made faster. However, they should only have to run once at the beginning of your script, because the results are cached using the @lru_cache(maxsize=32) statement. It should also be possible to implement caching that works across multiple runs.

That said, I don't know if the current code (including the stuff you run each epoch) would be fast enough for your use case. 256x256 is pretty big, even for a 2D CNN. A spherical CNN with SO(3) feature maps is more like a 3D CNN, and there a feature map of 256x256x256 is currently considered very large. Moreover, the SO(3) convolution code is less optimized than CUDA's 3D-Conv code. It's certainly not impossible to scale this up, but will take some engineering effort.

**Comment by antigol** [comment]
Now in af8768c23fa6a20267f4a9d0efaf69d2fd7d2231 these functions are cached on disk
