### ISSUE TITLE
About the parameter setting of the spherical CNNs

### ISSUE THREAD

**Issue by yudawen** [jonas-koehler/s2cnn#18]
What is the actual meaning of bandwidth in the paper and how it should be set?What can I set and adjust based on?

**Comment by yudawen** [comment]
@mariogeiger

**Comment by jonas-koehler** [comment]
Hope this is not a too lengthy explanation, but might spare similar questions for the future. Take from it whatever you need :-)

The S2CNN is a convolution for signals on the sphere. These are signals f:S^2 -> R^n. In our real discrete computer world, we do not really have a continuous representation of these signals. Thus we need to somehow represent them by a finite discrete set. This is done in our framework, by embedding such signals on a grid living on the sphere (similar as normal continuous images are embedded into discrete pixel grids).

Now our operation uses the Fourier transform on the sphere and SO(3) respectively in order to compute the equivariant convolution (correlation). Here we exploit the Fourier theorem, i.e. that convolutions can be represented as multiplications in Fourier space.

As said our signal is discretely represented on a grid. Thus applying such a (in principle continuous) convolution on this grid, boils down to a discrete Fourier transform in this space. As in the usual 1D Euclidean case, this transform can only be exact within a bandwidth B, which is dependent on the resolution of our actual signal (in Euclidean 1D its just the size N of the discrete array representing the signal). Precisely we have N = 2 * B given by the Nyquist-Shannon bound. 

In the concrete case, the bandwidth is depending on the resolution of our grid, which we define for S2 and SO(3) respectively. As both are higher-dimensional manifolds and the grids are not uniform, this is geometrically bit more involved than in the simple equispaced 1D case, but the idea is pretty much the same: B determines N=2*B which is the number of sample points along each axis of the two-/three-dimensional manifold S^2/SO(3).

For the current implementation, you should have a look into how your signals can be represented on grids over the sphere. E.g. the projection of MNIST on the sphere might give you a good start. Here we set a grid for S2, define its bandwidth, then project the images on this grid. Now the chosen bandwidth determines how many grid points we have. So if we represent our S2/SO(3) signal by a 2D/3D tensor, it gives us dimensions 2*b x 2*b and 2*b x 2*b x 2*b respectively.

Accordingly, this sets the bandwidth for our Fourier based convolutions: **b_in** determines the bandwidth of the incoming signal, **b_out** determines the bandwidth of the outgoing signal. You can see that similar to normal 2D convolutions, where images get compressed to smaller dimensional filters along the way.

**Comment by yudawen** [comment]
@jonas-koehler Thank you very much for explaining this to me patiently.I read your paper carefully and your research is very meaningful. But I still have some confusion.For example, I can clearly understand planar CNN, the meaning of stride, the meaning of the number of channels, pan by pixel and then do related operations. But throw away the formula,for spherical CNN, I don't understand how the specific operation process is, can you explain in general what is the process of the operation of the spherical CNN? From your explanation above, I know that the bandwidth will gradually decrease after S2/SO(3)convolution. From a convolutional layer to the next convolutional layer, how does the number of grid points decrease, and what is the law?

**Comment by meder411** [comment]
> Accordingly, this sets the bandwidth for our Fourier based convolutions: b_in determines the bandwidth of the incoming signal, b_out determines the bandwidth of the outgoing signal. You can see that similar to normal 2D convolutions, where images get compressed to smaller dimensional filters along the way.

Would a visual analog then be to picture the input sphere being of some radius `r`, and the output sphere of the layer to be some small radius `r / z` where `z` is some factor proportional to the ratio of **b_in** and **b_out**?

**Comment by meder411** [comment]
Gotcha, I misunderstood. Going off of your detailed explanation above, would bandwidth be more analogous to the receptive field then? If I'm looking at this like a discrete 1-D signal, the bandwidth of a convolutional filter is going to determine just how many discrete impulses (or however you like to describe them) we sample. Can we just look as this convolution operation as a sort of band-pass filter for a 3D signal?

**Comment by meder411** [comment]
You know what.... I'll check out Kostalec and Rockmore, 2007

**Comment by mariogeiger** [comment]
The convolution operation is : signal * filter
> the bandwidth of a convolutional filter
The signal has a certain size (that we call the input bandwidth), it is of shape `[batch, channel, alpha, beta, gamma] (batch_size, nbr_of_features, 2 * bandwidth, 2 * bandwidth, 2 * bandwidth)`
The filter has a support defined by `so3_***_grid`

Then both are Fourier transform into two Fourier functions of some size (that we call the output bandwidth), multiply together and finally Fourier transform back into "real" space.

> Can we just look as this convolution operation as a sort of band-pass filter for a 3D signal?
Band-pass filters are only a subset of what convolution can do on the signal.

**Comment by tscohen** [comment]
To put it simply: 2*bandwidth = resolution.

**Comment by yaoshunya** [comment]
I am Japanese courage student and want to run this program. but I use another dataset 'kitti'. I want to set images at the center of the sphere.

how can I set an image on the center of the sphere? 
i guess that rad_rotation_matrix's paragraph (theta,phi,z) can make.

**Comment by tscohen** [comment]
What do you mean by the center of the sphere? The spherical CNN only works on the surface of the sphere, not inside it. Do you mean the north pole (0, 0, 1)?
