### ISSUE TITLE
How to decide the bandwidth?

### ISSUE THREAD

**Issue by Jiankai-Sun** [jonas-koehler/s2cnn#22]
Firstly, thank you for the great work!

As the paper mentioned `The maximum frequency b is known as the bandwidth, and is related to the
resolution of the spatial grid (Kostelec and Rockmore, 2007).`

I notice that the bandwidth is set to 30 when you generate the new MNIST dataset. For each `S2Convolution` and `SO3Convolution`, the bandwidth is different. 

I wonder how to decide the parameter `bandwidth` when we use `S2Convolution` or `SO3Convolution`? Is it also a super parameter (empirical value) or need to be calculated meticulously?

Why you set `bandwidth = 30` when you generate the new MNIST dataset?

Thank you!

**Comment by tscohen** [comment]
Ultimately it is a hyperparameter, similar to the spatial resolution in a planar CNN. In a planar CNN this is purely determined by by the stride of the convolutions and the pooling, but in spherical CNNs you have more flexibility: you can in principle choose the resolution freely in each layer.

There are currently no good "best practices" for spherical CNN architecture design, and this includes the bandwidth/resolution, but there are a couple of considerations that would factor into the decision:
- Higher resolution means you can represent more small details
- Higher resolution means higher computational cost
- If you reduce the resolution too quickly, you would ignore units in the input, just like when you use 2D convolution with a stride that is larger than the filter size. 
- If the task is classification, you would typically start with a high resolution and gradually decrease it. The final layer can have very low resolution, and each unit has a receptive field that covers the whole input.
- If the task is e.g. segmentation, you could try a U-net like architecture.

We choose bandwidth=30 because it's not too large, but still allows us to represent MNIST digits without losing too much detail. MNIST images are 28x28, but we project them only on the top of the sphere, so using a spherical grid with 2*b=60 samples per dimension, we can represent it fairly accurately.

**Comment by Jiankai-Sun** [comment]
Thank you for your quick reply!

As the paper describes, `We created two instances of this dataset: one in which each digit is projected on the northern hemisphere and one in which each projected digit is additionally randomly rotated.` Why  do you just project on the northern hemisphere instead of the entire sphere? 

Thank you!

**Comment by Jiankai-Sun** [comment]
Also, for VGG Net, there are some [nn.MaxPool2d(kernel_size=2, stride=2)](https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py#L66) layers. Is there any implementations of MaxPool2d() operation or MaxPool3d() operation for Spherical CNN? Probably `so3_integrate()` is one possible solution as this [issue](https://github.com/jonas-koehler/s2cnn/issues/20) mentioned. However can we feed the output of `so3_integrate` as the input of the next SO3Convolution()?  I am afraid the shape is not appropriate. Or can we directly use [torch.nn.MaxPool2d](https://pytorch.org/docs/stable/nn.html#torch.nn.MaxPool2d) / [torch.nn.MaxPool3d](https://pytorch.org/docs/stable/nn.html#torch.nn.MaxPool3d) same as standard 2D CNN?

Thank you for your suggestion.

**Comment by Jiankai-Sun** [comment]
Great thanks to your quick reply! Your work is so  fascinating!
